---
- name: Create AWS Instances
  hosts: localhost
  gather_facts: False
  roles:
  - { name: create-rhel-7-4 }
  - { name: create-rhel-7-5 }
  - { name: create-centos }
  - { name: create-ubuntu }


    
    
    


