  - name: Create RHEL instance in ec2
    ec2:
      image: "{{ ami_name }}"
      instance_type: "{{ instance_size }}"
      key_name: "{{ ssh_key_name }}"
      region: "{{ region }}"
      wait: true
      instance_tags: "{'rhel', 'type':'{{ instance_type }}', 'group':'{{ security_group }}'}"
      vpc_subnet_id: "{{ subnet_id }}"
      assign_public_ip: yes
      group_id: "{{ security_group }}"  # or you can say 'default' here
    register: ec2-rhel
    tags: create

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
    tags: create

  - name: Enumerate all tagged instances in ec2
    ec2_instance_facts:
      region: 'ap-southeast-2'
      filters:
        "tag:Ansible": "{{ instance_tag }}" 
    register: vmfacts 
    tags: 
      - delete
      - create

  - debug: msg="{{ item.instance_id }}"
    with_items: '{{ vmfacts.instances }}'
    tags: 
      - delete 
      - create