    vm_count: 1
    security_group: 'sg-036c04403f8194aba'
    subnet_id: 'subnet-c3295a8a'
    ssh_key_name: 'etg-vinni'
    instance_size: 't2.micro'
    instance_tag: 'rhel'
    ami_name: 'ami-67589505'
    region: 'ap-southeast-2'  